<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUisecpe\srcShopware_Production_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUisecpe/srcShopware_Production_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerUisecpe.legacy');

    return;
}

if (!\class_exists(srcShopware_Production_KernelProdContainer::class, false)) {
    \class_alias(\ContainerUisecpe\srcShopware_Production_KernelProdContainer::class, srcShopware_Production_KernelProdContainer::class, false);
}

return new \ContainerUisecpe\srcShopware_Production_KernelProdContainer([
    'container.build_hash' => 'Uisecpe',
    'container.build_id' => '1f89066f',
    'container.build_time' => 1592412184,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUisecpe');
